title: Celso Crivelaro
email: celsocrivelaro at gmail.com
description: |
  Sharing a little bit of my experience and ideas.
baseurl: ''
url: 'https://crivelaro.me'
twitter_username: celsocrivelaro
github_username: celsocrivelaro
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
theme: minimal-mistakes-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
timezone: America/Sao_Paulo
authors:
  celso:
    display_name: Celso Crivelaro
    gravatar: 93e0d20852c0be7cee0aaa06e109f441
    email: celsocrivelaro@gmail.com
    web: 'https://crivelaro.me'
    github: celsocrivelaro
