# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Celso Crivelaro
email: celsocrivelaro at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing a little bit of my experience and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crivelaro.me" # the base hostname & protocol for your site
twitter_username: celsocrivelaro
github_username:  celsocrivelaro

# Build settings
markdown: kramdown

plugins: [jekyll-sitemap]

remote_theme: "jekyll/minima"

exclude: ['s3_website.yml', 'Gemfile', 'Gemfile.lock', 'deploy.sh', '.gitignore', 'deploy.sh']
timezone: America/Sao_Paulo

authors:
  celso: 
    display_name: Celso Crivelaro
    gravatar: 93e0d20852c0be7cee0aaa06e109f441
    email: celsocrivelaro@gmail.com
    web: https://crivelaro.me
    twitter: celsocrivelaro
    github: celsocrivelaro
